### ISSUE TITLE
Ordering of proposal not always intuitive

### ISSUE THREAD

**Issue by dscopra** [BADF00D/InternalsVisibleToFixer#7]
Imaging I have the following projects:
* SomeAssembly
* FirstAssembly
* Short
* AnotherAssembly

Currently I'm editing the AssemblyInfo in project AnotherAssembly. When I type _Some_ my proposals have the following order:
* Short
* SomeAssembly

But obviously I was trying to type SomeAssembly, so this should be my first proposal.

Furthermore it would be nice to have a case sensitive search like I have in ReSharper. It make some kind of Regex search. For "SA" it would propose "SomeAssembly" first, because it has the same upper case letters

**Comment by BADF00D** [comment]
Fixed in release 0.4
